version: '3.8'
services:
  navigation-frontend:
    build: ./navigation-frontend
    ports:
      - "6999:6999"
    networks:
      - backend-network

  book-managment-frontend:
    build: ./book-managment-frontend
    ports:
      - "7000:7000"
    networks:
      - backend-network

  reservation-managment-frontend:
    build: ./reservation-managment-frontend
    ports:
      - "7003:7003"
    networks:
      - backend-network

  user-managment-frontend:
    build: ./user-managment-frontend
    ports:
      - "7002:7002"
    networks:
      - backend-network

networks:
  backend-network:
    external: true
